tools/mosaic.py
Same as STScI-JWST/wss_tools#24 minus release prep.
p.s. @bhilbert4 , didn't realized you made this repo public. Was that intentional?
=> Fix orientation of NIRCam mosaic

tools/image_orientation/sci2ssb.py
Needed to run with JWST Pipeline Build 7
=> Update import for jwst models in sci2ssb.py

reffile_creation/pipeline/gain/create_gain_files.py, reffile_creation/pipeline/gain/gain_reffile.py
Initial version. This code saves an existing gain array using the datamodels, but does not create the array itself. Also added code for creating the quick CV3 gain from Armin using limited data, to replace the files from UofA
=> Added files for creating gain reference files using datamodel

reffile_creation/pipeline/gain/gain_reffile.py
Quick update to the function that saves a gain reference file.
=> small change to gain_reffiles.py

tools/image_orientation/nircam2ssb.py, tools/image_orientation/sci2ssb.py
Updated print and raise statements to be compatible with python 3. Also changed xrange to range.
=> Updated for python 3

nircam_calib/reffile_creation/pipeline/reffile_schema.py
Dictionary is part of the object's namespace. No need to return.
=> Removed unnecessary return statement

nircam_calib/pipeline_testing/jump_detection/jump_validation_tests.py
Added line to save out the slope of the jumps flagged
=> Added slopes

nircam_calib/reffile_creation/pipeline/persistence/persist_saturation.py
This is the first version of the script to make saturation reference files.
=> Added script to make saturation reference files

nircam_calib/reffile_creation/pipeline/gain/gain.py, nircam_calib/reffile_creation/pipeline/gain/gain_reffile.py, nircam_calib/reffile_creation/pipeline/gain/refpixcorr.py, nircam_calib/reffile_creation/pipeline/gain/texttable.py, nircam_calib/reffile_creation/pipeline/reffile_schema.py
Updated Armin's calcgainim.py to:
1) use my non-regular grid, to account for the epoxy void regions
2) function in python 3, as the jwst pipeline no longer supports python 2.
Import statements still need to be updated to work assuming installed nircam_calib package.
=> Created gain.py to be integrated with mkrefs

nircam_calib/reffile_creation/pipeline/calib_prep.py, nircam_calib/reffile_creation/pipeline/example_input_table.txt
calib_prep.py takes a list of files, reference file types, and associated pipeline steps, searches for input files, generates output filenames, and creates a list of the strun commands needed to produce the output files.
The input table is updated with the output filenames and necessary pipeline steps and returned. The list of strun commands is also returned.
=> Initial commit of calib_prep, which generates strun commands for mkrefs

nircam_calib/reffile_creation/pipeline/persistence/persist_saturation.py
Fixed code to prevent reference file delivery errors in the future
=> Updated script

nircam_calib/reffile_creation/pipeline/gain/gain.py
Input flat field file names were not being put into class variables, which were used to populate input filenames in the header of the output gain map file. Fixed.
=> Fixed a bug that was preventing flat filenames from being put in header

.gitignore, nircam_calib/reffile_creation/pipeline/gain/gain.py, nircam_calib/reffile_creation/pipeline/photom/photom.py
photom.py creates the flux calibration and pixel area map reference files. Initial commit before creating our first good reference files in the near future. 
Also added the low epoxy map for B3, which was missing. Small update to gain.py so that it knows about the B3 map.
=> Initial commit of photom.py, added .gitignore, added B3 low epoxy region

nircam_calib/pipeline_testing/README.md, nircam_calib/pipeline_testing/test_template_script.py
Added preliminary pytest template and README instructions for pipeline testing code contributions
=> Add pytest template

nircam_calib/reffile_creation/pipeline/superbias/average_superbiases.py, nircam_calib/reffile_creation/pipeline/superbias/calibrate_superbias_inputs_parallelized.py, nircam_calib/reffile_creation/pipeline/superbias/make_superbiases.py, nircam_calib/reffile_creation/pipeline/superbias/nn2.py, nircam_calib/reffile_creation/pipeline/superbias/refpixcorr_g0.py, nircam_calib/reffile_creation/pipeline/superbias/run_pipeline.py, nircam_calib/reffile_creation/pipeline/superbias/superbias_create_parallelized.py
I figured I could make some updates to the script as I was trying to get it to run. I just ran 2to3 on everything since some of the files had Python 2 syntax (print statements and xrange).
=> Updated Python2 syntax to Python3 with 2to3 program

nircam_calib/training_notebooks/NIRCam_Hack_Session_1.ipynb
I'm just uploading a brief walk-through notebook for the first NIRCam Hack Session. I figured we could store any training notebooks here for now. I'll go ahead and merge this since I didn't make any other changes.
=> Added notebook for first Hack Session

nircam_calib/training_notebooks/NIRCam_Hack_Session_1.ipynb
Made minor notebook changes to include setting up server environments and using screen utility.
=> Added server and screen info.

nircam_calib/pipeline_testing/superbias/test_bias_sub.py
The CalPipe Focus Group is sharing code. I am adding some of our test scripts refactored into unit tests for the pipeline -- if other teams review/agree to the tests, these will get merged into the jwst test code. For now, since they have to be reviewed before going anywhere, I'll just push this into our main repo. Unit test scripts will go in the "tests" directory for each step here https://github.com/spacetelescope/jwst.
=> Added unit tests for superbias subtraction

nircam_calib/pipeline_testing/saturation/test_saturation_flagging.py
The CalPipe Focus Group is sharing code. I am adding some of our test scripts refactored into unit tests for the pipeline -- if other teams review/agree to the tests, these will get merged into the jwst test code. For now, since they have to be reviewed before going anywhere, I'll just push this into our main repo. Unit test scripts will go in the "tests" directory for each step here https://github.com/spacetelescope/jwst.
=> Adding saturation unit tests for the pipeline

nircam_calib/pipeline_testing/saturation/test_saturation_flagging.py
Fixed script to include unit test for correct_for_NaN() instead of wrapping up NaN checks into the other unit tests to allow tool to determine code coverage.
=> Added missing unit test to increase code coverage

nircam_calib/training_notebooks/NIRCam_Hack_Session_1-Conda.ipynb, nircam_calib/training_notebooks/NIRCam_Hack_Session_2-MIRAGE.ipynb
@bhilbert4 are you okay with me adding your MIRAGE hack session notebook to the GitHub training notebooks?
=> Added notebook for 2nd Hack Session

nircam_calib/commissioning/flight2ground.py
Removed some extra lines of code that were not needed.
=> Remove extra code

nircam_calib/pipeline_testing/ncdhas_pipeline/ncdhas_dict.py, nircam_calib/pipeline_testing/ncdhas_pipeline/run_ncdhas_pipeline.py
I am adding some older scripts I wrote as a wrapper to run the NCDHAS pipeline, in case they are useful.
=> Add ncdhas code

nircam_calib/pipeline_testing/ncdhas_pipeline/run_ncdhas_pipeline.py
I forgot to take out an extra function that isn't used
=> Ncdhas edits

nircam_calib/commissioning/keyword_search.py
Added code to handle case where the input keyword was not found in the dictionary.
=> Add error handling

nircam_calib/GSEG/validate_GSEG_data.py
The script contains the same code as is presently in the notebook in the same directory. I'm including the script as well just in case that is easier for future development.
Note that this script and the notebook are dependent upon mirage.
=> Add GSEG data validation script

nircam_calib/commissioning/NRC_09_darks/NRC09_analysis_cross_talk.ipynb, nircam_calib/commissioning/NRC_09_darks/NRC09_analysis_fpa_asic_temperature.ipynb, nircam_calib/commissioning/NRC_09_darks/NRC09_analysis_hot_noisy_pixels.ipynb, nircam_calib/commissioning/NRC_09_darks/NRC09_analysis_ipc_characterization.ipynb, nircam_calib/commissioning/NRC_09_darks/NRC09_analysis_noise_stability_dark_current_performance.ipynb, nircam_calib/commissioning/NRC_09_darks/NRC09_analysis_pipeline_check.ipynb, nircam_calib/commissioning/NRC_09_darks/NRC09_analysis_readnoise_1overf_noise.ipynb, nircam_calib/commissioning/NRC_09_darks/NRC09_analysis_superbias.ipynb
Adding a second round of draft notebooks with minor (mostly formatting) updates to the first round of notebooks:
new file:   NRC09_analysis_cross_talk.ipynb
modified:   NRC09_analysis_fpa_asic_temperature.ipynb
modified:   NRC09_analysis_glow_signature.ipynb
new file:   NRC09_analysis_hot_noisy_pixels.ipynb
modified:   NRC09_analysis_ipc_characterization.ipynb
modified:   NRC09_analysis_noise_stability_dark_current_performance.ipynb
modified:   NRC09_analysis_pipeline_check.ipynb
modified:   NRC09_analysis_readnoise_1overf_noise.ipynb
new file:   NRC09_analysis_superbias.ipynb
Cell outputs are cleared.
=> Adding round two of draft notebooks

nircam_calib/reffile_creation/crds_completeness_check/nircam_crds_completeness_check.ipynb, nircam_calib/reffile_creation/pipeline/photom/photom.py
This PR contains updates to the code used to create photom (flux calibration) reference files, and some updates to the CRDS completeness check notebook
=> Updates to photom reffile creation and crds completeness check

nircam_calib/tools/image_orientation/sci2ssb.py
Fixed an error in sci2ssb script for output subarray start/stop headers.
=> Fixed typo in sci2ssb

nircam_calib/commissioning/NRC_10_flats/make_skyflat.py
This PR adds the initial code used to create the skyflat for NRC-10.
=> Add skyflat creation code for nrc-10

nircam_calib/commissioning/NRC_33_grismTS_stability/initial_checkouts/init_data_checks.ipynb
Notebook for initial data checks for CAR-33
=> notebook for initial data checks for CAR-33

nircam_calib/reffile_creation/pipeline/distortion/make_all_imaging_distortion_reffiles_from_pysiaf.py, nircam_calib/reffile_creation/pipeline/distortion/nircam_distortion_reffiles_from_pysiaf.py
Updates to scripts for making distortion reference files for coron modes.
=> Updates for coron files

nircam_calib/commissioning/NRC03_initial_functional_check/slope_stats.py
Just adding a few small functions that should be helpful in the analysis of the data tomorrow. Tweaks will be needed, but these will be a good starting point.
=> Basic functions to use for analysis of NRC-03 part 1

nircam_calib/reffile_creation/pipeline/distortion/make_all_imaging_distortion_reffiles_from_pysiaf.py, nircam_calib/reffile_creation/pipeline/distortion/nircam_distortion_reffiles_from_pysiaf.py
Just a couple small tweaks while helping Vera get set up to run the script.
=> Tweaks to distortion reference file creation script

nircam_calib/tools/snowballs/example_run_snowball_detector.py, nircam_calib/tools/snowballs/snowball_detector.py
This PR adds code that can be used to search NIRCam data for snowballs and make some basic plots/tables/images with results.
=> Add snowball detector 
